# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Release

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Check package version
      uses: MontyD/package-json-updated-action
      id: version-updated

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup yarn
    - run: npm install -g yarn

    - name: Build
      run: yarn && yarn build && ls -alh dist

    - name: Triger release with package.json
      uses: softprops/action-gh-release@v1
      if: steps.version-updated.outputs.has-updated
      with:
        files: dist/main.css
        tag_name: ${{ steps.version-updated.outputs.current-package-version }}

    - name: Publish with package.json
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
